### PR TITLE
Create the erd diagram for our tables

### PR DESCRIPTION
**Pull request by ZawadiSumba66**
In this milestone, we created the ERD Diagram to display the relationship between our tables which include: posts, users, comments, likes, and friendships

### CODE REVIEW

**Review by oloomoses — CHANGES_REQUESTED** [review]
# Status: Changes Required
**Hello team, this is a great start, your ERD is impressive :clap:
Check out some of the issues to fix :point_down:**

- [x] Kindly ensure that the linter is set up correctly and all checks are passing
- [ ] The relationship between a User and friendship table should look like this:
u

- [ ] Make sure to represent this in the erd using the appropriate connector like shown above. Same goes for the Post & User, Like & User, etc.

Kindly implement the above changes before submitting another code review.
### If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help
## HAPPY CODING 
_Slack: Oloo Moses_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Changes Required! :recycle:
### Hi @ZawadiSumba66 and @SamArsanios :clap: :clap:
#### Good job so far :+1: However, some requirements are missing/not implemented correctly. Check my comment below :point_down:

#### ERD:
 - The relationship between the user table and friendship table should be reflected in the ERD .i.e friendship has many `user_id` and `friend_id`. So you should draw two lines from the user to the friendship table.
 - Likewise, the ERD should reflect the relationship between the user and the post

#### _Reviewed by Temitayo Adeleke_

**Review by enaburekhan — CHANGES_REQUESTED** [review]
# Status: Request changes:full_moon:
**Hi team!
Great job so far on this milestone:clap::clap:. Everything looks perfect except for just one change we need to quickly make to get this project approved:muscle:.**

**To improve**

- [ ] Rename the p_id to post_id in the like table

image

Make the above-required change and when you are ready, request another review.
Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy coding:blush:
Eric Enaburekhan

**Review by peterrobert — APPROVED** [review]
### APPROVED 👍🏿 💯 
Hello, @ZawadiSumba66  👋🏿 . Great work. Good job making all the requested changes the project looks perfect to me 💯 . On to the next milestone 💪🏿 

### HAPPY CODING 💻

**Pull request merged**
